### PR TITLE
Updating documentation

### PR DESCRIPTION
**Pull request by edkazcarlson-ms**
This PR adds some documentation to the repo, making it easier to understand what the different classes and methods do.

### CODE REVIEW

**Comment by EasyRhinoMSFT** [comment]
@yongyan-gh is added to the review. #Closed

**Comment by edkazcarlson-ms** [comment]
@yongyan-gh Just wanted to make sure that this didn't get buried.

**Comment by EasyRhinoMSFT** [comment]
@yongyan-gh please focus on SarifErrorListItem

**Comment by yongyan-gh** [comment]
Looks good to me

---
In reply to: [1497867263](https://github.com/microsoft/sarif-visualstudio-extension/pull/590#issuecomment-1497867263) [](http://example.com/codeflow?ancestors=1497867263,1497867263)

**Pull request merged**
